[package]
name = "repofolio"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "folio — the reference CLI implementation of the Repofolio standard"

[dependencies]
serde_json.workspace = true
clap.workspace = true
anyhow.workspace = true
repofolio-core.workspace = true
repofolio-manifest.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
snapbox.workspace = true

[[bin]]
name = "folio"
path = "src/main.rs"
